### ISSUE TITLE
Problems with OBI "processed material"

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1718]
```yaml
class: OBI:0000047
name: processed material
def: "Is a material entity that is created or changed during material processing." []
equivalent_to: BFO:0000040 ! material entity
  and
  OBI:0000312 ! is_specified_output_of
  some OBI:0000094 ! material processing
```

material processing is defined as _A planned process which results in physical changes in a specified input material_
= achieves_planned_objective some 'material transformation objective'

which is itself defined as _an objective specifiction[sic] that creates an specific output object from input materials._

This doesn't specify what an input material is, neither does the def of objective specification.

1. The label for OBI:0000047 is misleading. "material" sounds like a mass noun rather than an object. It is odd to think of the Empire State Building as "material", yet I think it is intended to classify here. If this the intent the label should be "processed material entity"?
2. This is an injector class, it claims a broad variety of subclasses from multiple ontologies with different scopes, as such I think this is (inadvertently) violating https://obofoundry.org/principles/fp-005-delineated-content.html
3. It is inconsistently applied (inevitable, for an injector class). For example, we would expect to see the following under it:
   - IAO: photographic print
   - random access memory
   - guar gum
   - manufactured 

Or maybe I'm wrong and processed material should only be used for materials in the sense of substances, but there needs to be more guidance in what is included and what is excluded

__UPDATE__ I did not need to write so much, COB already uses the label "processed material entity" signaling intent. I think for now if OBI updates the label to sync with COB that is sufficient to close this issue for now, and we can take everything else to the COB tracker
